// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Phone.proto

package com.hbase.test;

public final class Phone {
  private Phone() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface phoneDetailOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string dnum = 1;
    /**
     * <code>required string dnum = 1;</code>
     */
    boolean hasDnum();
    /**
     * <code>required string dnum = 1;</code>
     */
    java.lang.String getDnum();
    /**
     * <code>required string dnum = 1;</code>
     */
    com.google.protobuf.ByteString
        getDnumBytes();

    // required string date = 2;
    /**
     * <code>required string date = 2;</code>
     */
    boolean hasDate();
    /**
     * <code>required string date = 2;</code>
     */
    java.lang.String getDate();
    /**
     * <code>required string date = 2;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    // required string length = 3;
    /**
     * <code>required string length = 3;</code>
     */
    boolean hasLength();
    /**
     * <code>required string length = 3;</code>
     */
    java.lang.String getLength();
    /**
     * <code>required string length = 3;</code>
     */
    com.google.protobuf.ByteString
        getLengthBytes();

    // required string type = 4;
    /**
     * <code>required string type = 4;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 4;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 4;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code com.hbase.test.PhoneDetail}
   */
  public static final class phoneDetail extends
      com.google.protobuf.GeneratedMessage
      implements phoneDetailOrBuilder {
    // Use phoneDetail.newBuilder() to construct.
    private phoneDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private phoneDetail(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final phoneDetail defaultInstance;
    public static phoneDetail getDefaultInstance() {
      return defaultInstance;
    }

    public phoneDetail getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private phoneDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              dnum_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              date_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              length_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              type_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hbase.test.Phone.internal_static_com_sxt_hbase_phoneDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hbase.test.Phone.internal_static_com_sxt_hbase_phoneDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hbase.test.Phone.phoneDetail.class, com.hbase.test.Phone.phoneDetail.Builder.class);
    }

    public static com.google.protobuf.Parser<phoneDetail> PARSER =
        new com.google.protobuf.AbstractParser<phoneDetail>() {
      public phoneDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new phoneDetail(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<phoneDetail> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string dnum = 1;
    public static final int DNUM_FIELD_NUMBER = 1;
    private java.lang.Object dnum_;
    /**
     * <code>required string dnum = 1;</code>
     */
    public boolean hasDnum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string dnum = 1;</code>
     */
    public java.lang.String getDnum() {
      java.lang.Object ref = dnum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dnum_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dnum = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDnumBytes() {
      java.lang.Object ref = dnum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dnum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string date = 2;
    public static final int DATE_FIELD_NUMBER = 2;
    private java.lang.Object date_;
    /**
     * <code>required string date = 2;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string date = 2;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string date = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string length = 3;
    public static final int LENGTH_FIELD_NUMBER = 3;
    private java.lang.Object length_;
    /**
     * <code>required string length = 3;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string length = 3;</code>
     */
    public java.lang.String getLength() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          length_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string length = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLengthBytes() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        length_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string type = 4;
    public static final int TYPE_FIELD_NUMBER = 4;
    private java.lang.Object type_;
    /**
     * <code>required string type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string type = 4;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      dnum_ = "";
      date_ = "";
      length_ = "";
      type_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDnum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDnumBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLengthBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDnumBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLengthBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hbase.test.Phone.phoneDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.test.Phone.phoneDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.test.Phone.phoneDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.test.Phone.phoneDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.test.Phone.phoneDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.test.Phone.phoneDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hbase.test.Phone.phoneDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hbase.test.Phone.phoneDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hbase.test.Phone.phoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.test.Phone.phoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hbase.test.Phone.phoneDetail prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hbase.test.PhoneDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hbase.test.Phone.phoneDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hbase.test.Phone.internal_static_com_sxt_hbase_phoneDetail_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hbase.test.Phone.internal_static_com_sxt_hbase_phoneDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hbase.test.Phone.phoneDetail.class, com.hbase.test.Phone.phoneDetail.Builder.class);
      }

      // Construct using com.hbase.test.Phone.phoneDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        dnum_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hbase.test.Phone.internal_static_com_sxt_hbase_phoneDetail_descriptor;
      }

      public com.hbase.test.Phone.phoneDetail getDefaultInstanceForType() {
        return com.hbase.test.Phone.phoneDetail.getDefaultInstance();
      }

      public com.hbase.test.Phone.phoneDetail build() {
        com.hbase.test.Phone.phoneDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hbase.test.Phone.phoneDetail buildPartial() {
        com.hbase.test.Phone.phoneDetail result = new com.hbase.test.Phone.phoneDetail(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dnum_ = dnum_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hbase.test.Phone.phoneDetail) {
          return mergeFrom((com.hbase.test.Phone.phoneDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hbase.test.Phone.phoneDetail other) {
        if (other == com.hbase.test.Phone.phoneDetail.getDefaultInstance()) return this;
        if (other.hasDnum()) {
          bitField0_ |= 0x00000001;
          dnum_ = other.dnum_;
          onChanged();
        }
        if (other.hasDate()) {
          bitField0_ |= 0x00000002;
          date_ = other.date_;
          onChanged();
        }
        if (other.hasLength()) {
          bitField0_ |= 0x00000004;
          length_ = other.length_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000008;
          type_ = other.type_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDnum()) {
          
          return false;
        }
        if (!hasDate()) {
          
          return false;
        }
        if (!hasLength()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hbase.test.Phone.phoneDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hbase.test.Phone.phoneDetail) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string dnum = 1;
      private java.lang.Object dnum_ = "";
      /**
       * <code>required string dnum = 1;</code>
       */
      public boolean hasDnum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string dnum = 1;</code>
       */
      public java.lang.String getDnum() {
        java.lang.Object ref = dnum_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          dnum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string dnum = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDnumBytes() {
        java.lang.Object ref = dnum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dnum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dnum = 1;</code>
       */
      public Builder setDnum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dnum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dnum = 1;</code>
       */
      public Builder clearDnum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dnum_ = getDefaultInstance().getDnum();
        onChanged();
        return this;
      }
      /**
       * <code>required string dnum = 1;</code>
       */
      public Builder setDnumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dnum_ = value;
        onChanged();
        return this;
      }

      // required string date = 2;
      private java.lang.Object date_ = "";
      /**
       * <code>required string date = 2;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string date = 2;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string date = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string date = 2;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 2;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 2;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        date_ = value;
        onChanged();
        return this;
      }

      // required string length = 3;
      private java.lang.Object length_ = "";
      /**
       * <code>required string length = 3;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string length = 3;</code>
       */
      public java.lang.String getLength() {
        java.lang.Object ref = length_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          length_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string length = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLengthBytes() {
        java.lang.Object ref = length_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          length_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string length = 3;</code>
       */
      public Builder setLength(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string length = 3;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000004);
        length_ = getDefaultInstance().getLength();
        onChanged();
        return this;
      }
      /**
       * <code>required string length = 3;</code>
       */
      public Builder setLengthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        length_ = value;
        onChanged();
        return this;
      }

      // required string type = 4;
      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string type = 4;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 4;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.hbase.test.PhoneDetail)
    }

    static {
      defaultInstance = new phoneDetail(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.hbase.test.PhoneDetail)
  }

  public interface dayPhoneDetailOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.hbase.test.PhoneDetail phoneDetails = 1;
    /**
     * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
     */
    java.util.List<com.hbase.test.Phone.phoneDetail> 
        getPhoneDetailsList();
    /**
     * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
     */
    com.hbase.test.Phone.phoneDetail getPhoneDetails(int index);
    /**
     * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
     */
    int getPhoneDetailsCount();
    /**
     * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
     */
    java.util.List<? extends com.hbase.test.Phone.phoneDetailOrBuilder> 
        getPhoneDetailsOrBuilderList();
    /**
     * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
     */
    com.hbase.test.Phone.phoneDetailOrBuilder getPhoneDetailsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.sxt.hbase.dayPhoneDetail}
   */
  public static final class dayPhoneDetail extends
      com.google.protobuf.GeneratedMessage
      implements dayPhoneDetailOrBuilder {
    // Use dayPhoneDetail.newBuilder() to construct.
    private dayPhoneDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private dayPhoneDetail(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final dayPhoneDetail defaultInstance;
    public static dayPhoneDetail getDefaultInstance() {
      return defaultInstance;
    }

    public dayPhoneDetail getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private dayPhoneDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                phoneDetails_ = new java.util.ArrayList<com.hbase.test.Phone.phoneDetail>();
                mutable_bitField0_ |= 0x00000001;
              }
              phoneDetails_.add(input.readMessage(com.hbase.test.Phone.phoneDetail.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          phoneDetails_ = java.util.Collections.unmodifiableList(phoneDetails_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hbase.test.Phone.internal_static_com_sxt_hbase_dayPhoneDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hbase.test.Phone.internal_static_com_sxt_hbase_dayPhoneDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hbase.test.Phone.dayPhoneDetail.class, com.hbase.test.Phone.dayPhoneDetail.Builder.class);
    }

    public static com.google.protobuf.Parser<dayPhoneDetail> PARSER =
        new com.google.protobuf.AbstractParser<dayPhoneDetail>() {
      public dayPhoneDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new dayPhoneDetail(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<dayPhoneDetail> getParserForType() {
      return PARSER;
    }

    // repeated .com.hbase.test.PhoneDetail phoneDetails = 1;
    public static final int PHONEDETAILS_FIELD_NUMBER = 1;
    private java.util.List<com.hbase.test.Phone.phoneDetail> phoneDetails_;
    /**
     * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
     */
    public java.util.List<com.hbase.test.Phone.phoneDetail> getPhoneDetailsList() {
      return phoneDetails_;
    }
    /**
     * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
     */
    public java.util.List<? extends com.hbase.test.Phone.phoneDetailOrBuilder> 
        getPhoneDetailsOrBuilderList() {
      return phoneDetails_;
    }
    /**
     * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
     */
    public int getPhoneDetailsCount() {
      return phoneDetails_.size();
    }
    /**
     * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
     */
    public com.hbase.test.Phone.phoneDetail getPhoneDetails(int index) {
      return phoneDetails_.get(index);
    }
    /**
     * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
     */
    public com.hbase.test.Phone.phoneDetailOrBuilder getPhoneDetailsOrBuilder(
        int index) {
      return phoneDetails_.get(index);
    }

    private void initFields() {
      phoneDetails_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getPhoneDetailsCount(); i++) {
        if (!getPhoneDetails(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < phoneDetails_.size(); i++) {
        output.writeMessage(1, phoneDetails_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < phoneDetails_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, phoneDetails_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hbase.test.Phone.dayPhoneDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.test.Phone.dayPhoneDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.test.Phone.dayPhoneDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.test.Phone.dayPhoneDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.test.Phone.dayPhoneDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.test.Phone.dayPhoneDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hbase.test.Phone.dayPhoneDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hbase.test.Phone.dayPhoneDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hbase.test.Phone.dayPhoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.test.Phone.dayPhoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hbase.test.Phone.dayPhoneDetail prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sxt.hbase.dayPhoneDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hbase.test.Phone.dayPhoneDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hbase.test.Phone.internal_static_com_sxt_hbase_dayPhoneDetail_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hbase.test.Phone.internal_static_com_sxt_hbase_dayPhoneDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hbase.test.Phone.dayPhoneDetail.class, com.hbase.test.Phone.dayPhoneDetail.Builder.class);
      }

      // Construct using com.hbase.test.Phone.dayPhoneDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPhoneDetailsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (phoneDetailsBuilder_ == null) {
          phoneDetails_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          phoneDetailsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hbase.test.Phone.internal_static_com_sxt_hbase_dayPhoneDetail_descriptor;
      }

      public com.hbase.test.Phone.dayPhoneDetail getDefaultInstanceForType() {
        return com.hbase.test.Phone.dayPhoneDetail.getDefaultInstance();
      }

      public com.hbase.test.Phone.dayPhoneDetail build() {
        com.hbase.test.Phone.dayPhoneDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hbase.test.Phone.dayPhoneDetail buildPartial() {
        com.hbase.test.Phone.dayPhoneDetail result = new com.hbase.test.Phone.dayPhoneDetail(this);
        int from_bitField0_ = bitField0_;
        if (phoneDetailsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            phoneDetails_ = java.util.Collections.unmodifiableList(phoneDetails_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.phoneDetails_ = phoneDetails_;
        } else {
          result.phoneDetails_ = phoneDetailsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hbase.test.Phone.dayPhoneDetail) {
          return mergeFrom((com.hbase.test.Phone.dayPhoneDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hbase.test.Phone.dayPhoneDetail other) {
        if (other == com.hbase.test.Phone.dayPhoneDetail.getDefaultInstance()) return this;
        if (phoneDetailsBuilder_ == null) {
          if (!other.phoneDetails_.isEmpty()) {
            if (phoneDetails_.isEmpty()) {
              phoneDetails_ = other.phoneDetails_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePhoneDetailsIsMutable();
              phoneDetails_.addAll(other.phoneDetails_);
            }
            onChanged();
          }
        } else {
          if (!other.phoneDetails_.isEmpty()) {
            if (phoneDetailsBuilder_.isEmpty()) {
              phoneDetailsBuilder_.dispose();
              phoneDetailsBuilder_ = null;
              phoneDetails_ = other.phoneDetails_;
              bitField0_ = (bitField0_ & ~0x00000001);
              phoneDetailsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPhoneDetailsFieldBuilder() : null;
            } else {
              phoneDetailsBuilder_.addAllMessages(other.phoneDetails_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPhoneDetailsCount(); i++) {
          if (!getPhoneDetails(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hbase.test.Phone.dayPhoneDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hbase.test.Phone.dayPhoneDetail) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.hbase.test.PhoneDetail phoneDetails = 1;
      private java.util.List<com.hbase.test.Phone.phoneDetail> phoneDetails_ =
        java.util.Collections.emptyList();
      private void ensurePhoneDetailsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          phoneDetails_ = new java.util.ArrayList<com.hbase.test.Phone.phoneDetail>(phoneDetails_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.hbase.test.Phone.phoneDetail, com.hbase.test.Phone.phoneDetail.Builder, com.hbase.test.Phone.phoneDetailOrBuilder> phoneDetailsBuilder_;

      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public java.util.List<com.hbase.test.Phone.phoneDetail> getPhoneDetailsList() {
        if (phoneDetailsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phoneDetails_);
        } else {
          return phoneDetailsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public int getPhoneDetailsCount() {
        if (phoneDetailsBuilder_ == null) {
          return phoneDetails_.size();
        } else {
          return phoneDetailsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public com.hbase.test.Phone.phoneDetail getPhoneDetails(int index) {
        if (phoneDetailsBuilder_ == null) {
          return phoneDetails_.get(index);
        } else {
          return phoneDetailsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public Builder setPhoneDetails(
          int index, com.hbase.test.Phone.phoneDetail value) {
        if (phoneDetailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneDetailsIsMutable();
          phoneDetails_.set(index, value);
          onChanged();
        } else {
          phoneDetailsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public Builder setPhoneDetails(
          int index, com.hbase.test.Phone.phoneDetail.Builder builderForValue) {
        if (phoneDetailsBuilder_ == null) {
          ensurePhoneDetailsIsMutable();
          phoneDetails_.set(index, builderForValue.build());
          onChanged();
        } else {
          phoneDetailsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public Builder addPhoneDetails(com.hbase.test.Phone.phoneDetail value) {
        if (phoneDetailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneDetailsIsMutable();
          phoneDetails_.add(value);
          onChanged();
        } else {
          phoneDetailsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public Builder addPhoneDetails(
          int index, com.hbase.test.Phone.phoneDetail value) {
        if (phoneDetailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneDetailsIsMutable();
          phoneDetails_.add(index, value);
          onChanged();
        } else {
          phoneDetailsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public Builder addPhoneDetails(
          com.hbase.test.Phone.phoneDetail.Builder builderForValue) {
        if (phoneDetailsBuilder_ == null) {
          ensurePhoneDetailsIsMutable();
          phoneDetails_.add(builderForValue.build());
          onChanged();
        } else {
          phoneDetailsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public Builder addPhoneDetails(
          int index, com.hbase.test.Phone.phoneDetail.Builder builderForValue) {
        if (phoneDetailsBuilder_ == null) {
          ensurePhoneDetailsIsMutable();
          phoneDetails_.add(index, builderForValue.build());
          onChanged();
        } else {
          phoneDetailsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public Builder addAllPhoneDetails(
          java.lang.Iterable<? extends com.hbase.test.Phone.phoneDetail> values) {
        if (phoneDetailsBuilder_ == null) {
          ensurePhoneDetailsIsMutable();
          super.addAll(values, phoneDetails_);
          onChanged();
        } else {
          phoneDetailsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public Builder clearPhoneDetails() {
        if (phoneDetailsBuilder_ == null) {
          phoneDetails_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          phoneDetailsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public Builder removePhoneDetails(int index) {
        if (phoneDetailsBuilder_ == null) {
          ensurePhoneDetailsIsMutable();
          phoneDetails_.remove(index);
          onChanged();
        } else {
          phoneDetailsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public com.hbase.test.Phone.phoneDetail.Builder getPhoneDetailsBuilder(
          int index) {
        return getPhoneDetailsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public com.hbase.test.Phone.phoneDetailOrBuilder getPhoneDetailsOrBuilder(
          int index) {
        if (phoneDetailsBuilder_ == null) {
          return phoneDetails_.get(index);  } else {
          return phoneDetailsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public java.util.List<? extends com.hbase.test.Phone.phoneDetailOrBuilder> 
           getPhoneDetailsOrBuilderList() {
        if (phoneDetailsBuilder_ != null) {
          return phoneDetailsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phoneDetails_);
        }
      }
      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public com.hbase.test.Phone.phoneDetail.Builder addPhoneDetailsBuilder() {
        return getPhoneDetailsFieldBuilder().addBuilder(
            com.hbase.test.Phone.phoneDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public com.hbase.test.Phone.phoneDetail.Builder addPhoneDetailsBuilder(
          int index) {
        return getPhoneDetailsFieldBuilder().addBuilder(
            index, com.hbase.test.Phone.phoneDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .com.hbase.test.PhoneDetail phoneDetails = 1;</code>
       */
      public java.util.List<com.hbase.test.Phone.phoneDetail.Builder> 
           getPhoneDetailsBuilderList() {
        return getPhoneDetailsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.hbase.test.Phone.phoneDetail, com.hbase.test.Phone.phoneDetail.Builder, com.hbase.test.Phone.phoneDetailOrBuilder> 
          getPhoneDetailsFieldBuilder() {
        if (phoneDetailsBuilder_ == null) {
          phoneDetailsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.hbase.test.Phone.phoneDetail, com.hbase.test.Phone.phoneDetail.Builder, com.hbase.test.Phone.phoneDetailOrBuilder>(
                  phoneDetails_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          phoneDetails_ = null;
        }
        return phoneDetailsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.sxt.hbase.dayPhoneDetail)
    }

    static {
      defaultInstance = new dayPhoneDetail(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.sxt.hbase.dayPhoneDetail)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sxt_hbase_phoneDetail_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sxt_hbase_phoneDetail_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sxt_hbase_dayPhoneDetail_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sxt_hbase_dayPhoneDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Phone.proto\022\rcom.sxt.hbase\"G\n\013phoneDet" +
      "ail\022\014\n\004dnum\030\001 \002(\t\022\014\n\004date\030\002 \002(\t\022\016\n\006lengt" +
      "h\030\003 \002(\t\022\014\n\004type\030\004 \002(\t\"B\n\016dayPhoneDetail\022" +
      "0\n\014phoneDetails\030\001 \003(\0132\032.com.sxt.hbase.ph" +
      "oneDetail"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_sxt_hbase_phoneDetail_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_sxt_hbase_phoneDetail_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sxt_hbase_phoneDetail_descriptor,
              new java.lang.String[] { "Dnum", "Date", "Length", "Type", });
          internal_static_com_sxt_hbase_dayPhoneDetail_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_sxt_hbase_dayPhoneDetail_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sxt_hbase_dayPhoneDetail_descriptor,
              new java.lang.String[] { "PhoneDetails", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}

